### ISSUE TITLE
Official extension now available 

### ISSUE THREAD

**Issue by fregante** [ctf0/ghosttext-vscode#4]
Hello, I finally published the official extension for VS Code:

- https://github.com/fregante/GhostText-for-VSCode
- https://marketplace.visualstudio.com/items?itemName=fregante.ghost-text

I invite you to test it out, report any issues you see and contribute, if you have time. This is meant to replace the 3 forks currently available on the marketplace with a single, maintained, official version.

**Comment by ctf0** [comment]
ok awesome, thank you for the headsup
